resources:
  - name: app
    type: git
    source:
      uri: https://github.com/gerred/concourse_phoenix_example.git
      branch: master

jobs:
  - name: phoenix-unit
    plan:
      - get: app
        trigger: true
      - task: unit
        file: app/ci/unit/task.yml
